# Generated by Django 4.2.3 on 2023-07-26 23:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_key',
            field=models.TextField(blank=True, null=True, verbose_name=uuid.UUID('06768ab6-8791-4219-a3f8-ce50ab744336')),
        ),
    ]
