# Generated by Django 4.2.3 on 2023-07-27 01:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verification_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_key',
            field=models.TextField(blank=True, null=True, verbose_name=uuid.UUID('0c1c3af0-1593-4101-9307-ad4c53e48a12')),
        ),
    ]
