# Generated by Django 4.2.3 on 2023-08-02 21:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_verification_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_key',
            field=models.TextField(blank=True, null=True, verbose_name=uuid.UUID('36b63c21-ca3d-4e56-814b-71d7d0b93748')),
        ),
    ]
