# Generated by Django 4.2.3 on 2023-08-03 22:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_verification_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_key',
            field=models.TextField(blank=True, null=True, verbose_name=uuid.UUID('eef6c6f7-3150-4350-972b-d38da2a3ca70')),
        ),
    ]
