# Generated by Django 4.2.3 on 2023-08-05 00:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_verification_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_key',
            field=models.TextField(blank=True, null=True, verbose_name=uuid.UUID('28ebd25d-4038-402a-a02d-d0830fc85b57')),
        ),
    ]
