# Generated by Django 4.2.3 on 2023-08-05 18:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_verification_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_key',
            field=models.TextField(blank=True, null=True, verbose_name=uuid.UUID('4c8b6c30-4f90-4e1e-9e11-2657154a6e84')),
        ),
    ]
