# Generated by Django 4.2.3 on 2023-11-06 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_verification_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='название клиента, поставщика, завода'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_key',
            field=models.TextField(blank=True, null=True, verbose_name=uuid.UUID('26b6642b-8593-4bbc-8f17-4e986d25e53b')),
        ),
    ]
