# Generated by Django 4.2.3 on 2023-11-06 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_id_name_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_key',
            field=models.TextField(blank=True, null=True, verbose_name=uuid.UUID('c80550df-67d1-4e25-9ccc-9f708cb13b8c')),
        ),
    ]
