# Generated by Django 4.2.3 on 2023-08-02 21:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Контактный email')),
                ('client', models.CharField(max_length=100, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тема письма')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержимое письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='SmsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.TimeField(default=datetime.datetime(2023, 8, 2, 21, 10, 35, 579240, tzinfo=datetime.timezone.utc), verbose_name='Время рассылки')),
                ('frequency', models.CharField(choices=[('day', 'Раз в день'), ('week', 'Раз в неделю'), ('month', 'Раз в месяц')], default='', max_length=10, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('finished', 'Завершена')], default='Создание', max_length=10, verbose_name='Статус рассылки')),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_letters', to='send_emails.client', verbose_name='Клиент')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_emails.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Смс рассылка',
                'verbose_name_plural': 'Смс рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Неудачно')], max_length=10, verbose_name='Статус попытки')),
                ('server_response', models.TextField(verbose_name='Ответ почтового сервера, если он был')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_emails.mailing', verbose_name='Рассылка')),
                ('send_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_emails.smsletter', verbose_name='время рассылки')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
