# Generated by Django 4.2.3 on 2023-08-03 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsletter',
            name='send_time',
            field=models.TimeField(default=datetime.datetime(2023, 8, 3, 22, 39, 31, 546347, tzinfo=datetime.timezone.utc), verbose_name='Время рассылки'),
        ),
    ]
