# Generated by Django 4.2.3 on 2023-08-05 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_emails', '0002_alter_smsletter_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsletter',
            name='send_time',
            field=models.TimeField(default=datetime.datetime(2023, 8, 5, 0, 27, 45, 504492, tzinfo=datetime.timezone.utc), verbose_name='Время рассылки'),
        ),
    ]
