# Generated by Django 4.2.3 on 2023-11-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seller_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='адрес поставщика, завода'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='id_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='название поставщика, завода'),
        ),
    ]
